name: CI

on:
  push:
    branches: [ developments ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1

    - name: Build with Maven
      run: |-
        mvn --batch-mode --update-snapshots verify
        mkdir staging && cp target/*.jar staging

    - name: Publish to GitHub Packages Apache Maven
    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: staging
