name: CI

on:
  push:
    branches: [ developments ]

jobs:
  build_and_release:
    name: ビルド & リリース
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
    - name: 成果物を作成
    - run: mvn --batch-mode --update-snapshots verify
    - run: mkdir staging && cp target/*.jar staging
    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: staging
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
